(function(){'use strict';
const API=()=>window._cfApi?.()||window.WORKER_URL,H=()=>window._cfHdrs?.()||{},E=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state={};
async function req(path,opt={}){const r=await fetch(`${API()}/api/automation-center${path}`,{...opt,headers:{...H(),...(opt.body?{'Content-Type':'application/json'}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.validation_errors?.join(', ')||`HTTP ${r.status}`);return d;}
const pill=s=>`<span class="pill ${s==='active'||s==='completed'||s==='ready'?'ok':s==='dry_run'||s==='waiting_approval'?'warning':s==='disabled'?'gray':'danger'}">${E(s||'—')}</span>`;
async function render(){const el=document.getElementById('page-automation-center');if(!el)return;el.innerHTML='<div style="padding:32px;text-align:center">Ładowanie automatyzacji…</div>';try{state=await req('/overview');draw();}catch(ex){el.innerHTML=`<div class="empty-state"><i class="ti ti-database-off"></i><p>${E(ex.message)}</p><small>Wymagana jest ręczna migracja v57.</small></div>`;}}
function draw(){const el=document.getElementById('page-automation-center');el.innerHTML=`<div class="page-header"><div><h2><i class="ti ti-bolt"></i> Automatyzacje kosztowe</h2><p style="font-size:12px;color:var(--text3)">Reguły są wyjaśnialne, wersjonowane i domyślnie działają jako dry-run.</p></div><button class="btn btn-gray" onclick="AutomationCenter.render()">Odśwież</button></div>
<div style="display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:10px;margin-bottom:16px">${[['Reguły',state.rules?.length],['Otwarte alerty paliwa',state.fuel_alerts?.length],['Akcje do decyzji',state.actions?.length],['Dokumenty ERP',state.erp_documents?.length]].map(x=>`<div class="card" style="padding:14px"><b style="font-size:24px">${x[1]||0}</b><div style="font-size:11px">${x[0]}</div></div>`).join('')}</div>
<section class="card" style="padding:18px"><h3>Reguły zdarzenie → warunek → akcja</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Reguła</th><th>Tryb</th><th>Akcja</th><th>Bramka</th><th></th></tr></thead><tbody>${(state.rules||[]).map(r=>`<tr><td><strong>${E(r.name)}</strong><br><small>${E(r.rule_key)} · v${r.version}</small></td><td>${pill(r.mode)}</td><td>${E(r.action_type)}</td><td>${r.approval_required?'wymagana':'automatyczna'}</td><td><button class="btn btn-gray btn-sm" onclick="AutomationCenter.run('${E(r.id)}')" ${['fuel_gps_anomaly','service_authorization'].includes(r.rule_key)?'':'disabled'}>Dry-run / uruchom</button> <select class="fi" style="width:auto" onchange="AutomationCenter.mode('${E(r.id)}',this.value)"><option value="">Zmień tryb…</option><option value="dry_run">Dry-run</option><option value="active">Aktywna</option><option value="disabled">Wyłączona</option></select></td></tr>`).join('')}</tbody></table></div></section>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px"><section class="card" style="padding:18px"><h3>Paliwo ↔ GPS</h3>${(state.fuel_alerts||[]).slice(0,20).map(a=>`<div style="padding:8px;border-bottom:1px solid var(--border)"><strong>${E(a.vehicle_reg)}</strong> · score ${a.score} ${pill(a.severity)}<br><small>${E(JSON.parse(a.reason_codes||'[]').join(', '))}</small></div>`).join('')||'<p style="color:var(--text3)">Brak utrwalonych alertów. Uruchom dry-run, potem świadomie aktywuj regułę.</p>'}</section>
<section class="card" style="padding:18px"><h3>Leasing ↔ harmonogram danych</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input class="fi" id="ac-contract" placeholder="Numer umowy"><input class="fi" id="ac-reg" placeholder="Nr rejestracyjny"><input class="fi" id="ac-principal" type="number" placeholder="Kapitał PLN"><input class="fi" id="ac-count" type="number" value="48" placeholder="Liczba rat"><input class="fi" id="ac-interest" type="number" step="0.01" value="7.5" placeholder="Odsetki %"><input class="fi" id="ac-margin" type="number" step="0.01" value="1.5" placeholder="Marża %"><input class="fi" id="ac-residual" type="number" value="0" placeholder="Wykup"><input class="fi" id="ac-first" type="date"></div><button class="btn btn-blue" style="margin-top:8px" onclick="AutomationCenter.leasing(false)">Podgląd</button> <button class="btn btn-green" style="margin-top:8px" onclick="AutomationCenter.leasing(true)">Zapisz szkic</button><div id="ac-leasing-preview" style="margin-top:8px;font-size:12px"></div></section>
<section class="card" style="padding:18px"><h3>Szkoda ↔ FNOL</h3><p style="font-size:12px;color:var(--text3)">Podaj ID istniejącej szkody. System sprawdzi datę, opis, pojazd i polisę przed oznaczeniem zgłoszenia jako gotowe.</p><input class="fi" id="ac-claim" placeholder="ID szkody"><button class="btn btn-blue" onclick="AutomationCenter.fnol()">Przygotuj FNOL</button></section>
<section class="card" style="padding:18px"><h3>Rozliczenie ↔ ERP</h3><p style="font-size:12px;color:var(--text3)">Tworzy wersjonowany dokument wymiany z checksumą. Nie wysyła go do ERP.</p><input class="fi" id="ac-settlement" placeholder="ID zaakceptowanego rozliczenia"><select class="fi" id="ac-erp"><option value="erpnext">ERPNext</option><option value="enova365">enova365</option><option value="comarch">Comarch ERP XL / Optima</option></select><button class="btn btn-blue" onclick="AutomationCenter.erp()">Przygotuj dokument</button></section></div>
<section class="card" style="padding:18px;margin-top:16px"><h3>Explainable log</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Czas</th><th>Status</th><th>Dopasowania</th><th>Akcje</th><th>Wyjaśnienie</th></tr></thead><tbody>${(state.executions||[]).map(x=>`<tr><td>${E((x.started_at||'').slice(0,16))}</td><td>${pill(x.status)}</td><td>${x.matched_count}</td><td>${x.action_count}</td><td><code style="font-size:10px">${E(x.explanation)}</code></td></tr>`).join('')||'<tr><td colspan="5">Brak wykonań</td></tr>'}</tbody></table></div></section>`;}
async function run(id){try{const d=await req(`/rules/${id}/run`,{method:'POST',body:JSON.stringify({correlation_id:`manual:${id}:${Date.now()}`})});window.toast?.(`✅ ${d.execution.status}: ${d.execution.matched_count} dopasowań`);await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
async function mode(id,value){if(!value)return;if(value==='active'&&!confirm('Aktywować regułę? Może tworzyć trwałe alerty lub wnioski o zatwierdzenie.'))return render();try{await req(`/rules/${id}/mode`,{method:'POST',body:JSON.stringify({mode:value})});await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
function leasingBody(){return{contract_ref:document.getElementById('ac-contract').value,vehicle_reg:document.getElementById('ac-reg').value,principal_amount:+document.getElementById('ac-principal').value,installment_count:+document.getElementById('ac-count').value,annual_interest_pct:+document.getElementById('ac-interest').value,annual_margin_pct:+document.getElementById('ac-margin').value,residual_amount:+document.getElementById('ac-residual').value,first_due_date:document.getElementById('ac-first').value,vat_rate:.23};}
async function leasing(commit){try{const d=await req(`/leasing/${commit?'commit':'preview'}`,{method:'POST',body:JSON.stringify(leasingBody())});if(commit){window.toast?.(`✅ Zapisano ${d.installments} rat`);await render();}else{const rows=d.installments||[],sum=k=>rows.reduce((a,r)=>a+Number(r[k]||0),0);document.getElementById('ac-leasing-preview').textContent=`${rows.length} rat · kapitał ${sum('principal_amount').toFixed(2)} · odsetki ${sum('interest_amount').toFixed(2)} · marża ${sum('margin_amount').toFixed(2)} PLN`;}}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
async function fnol(){try{const d=await req(`/fnol/${encodeURIComponent(document.getElementById('ac-claim').value)}`,{method:'POST',body:'{}'});window.toast?.(`✅ FNOL: ${d.status}`);await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
async function erp(){try{const d=await req('/erp-documents',{method:'POST',body:JSON.stringify({settlement_id:document.getElementById('ac-settlement').value,adapter_key:document.getElementById('ac-erp').value})});window.toast?.(`✅ Dokument ERP: ${d.document.status}`);await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
window.AutomationCenter={render,run,mode,leasing,fnol,erp};})();
