(function(){
  'use strict';
  const API=()=>window._cfApi?.()||window.WORKER_URL,H=()=>window._cfHdrs?.()||{},E=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const FIELDS=['external_id','title','origin','destination','scheduled_start','scheduled_end','distance_km','cargo_desc','cargo_weight_kg','priority'];
  let state={formats:[],adapters:[],profiles:[],runs:[],schedules:[]},rows=[],file=null,preview=null;
  async function req(path,opt={}){const r=await fetch(`${API()}/api/integration-hub${path}`,{...opt,headers:{...H(),...(opt.body?{'Content-Type':'application/json'}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d;}
  async function render(){const el=document.getElementById('page-integration-hub');if(!el)return;el.innerHTML='<div style="padding:32px;text-align:center;color:var(--text3)"><i class="ti ti-loader"></i> Ładowanie centrum integracji…</div>';try{state=await req('/overview');draw();}catch(ex){el.innerHTML=`<div class="empty-state"><i class="ti ti-database-off"></i><p>${E(ex.message)}</p><small>Wymagana jest ręczna migracja v56.</small></div>`;}}
  function badge(s){const c=s==='completed'||s==='active'?'ok':s==='waiting_user'||s==='degraded'?'warning':s==='dead_letter'?'danger':'gray';return `<span class="pill ${c}">${E(s||'—')}</span>`;}
  function draw(){const el=document.getElementById('page-integration-hub');if(!el)return;el.innerHTML=`
    <div class="page-header"><div><h2><i class="ti ti-arrows-exchange"></i> Centrum integracji</h2><p style="color:var(--text3);font-size:12px">Jeden punkt importu, eksportu, mapowania i monitorowania konektorów.</p></div><button class="btn btn-gray" onclick="IntegrationHub.render()"><i class="ti ti-refresh"></i>Odśwież</button></div>
    <div style="display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:10px;margin-bottom:18px">
      ${[['Adaptery',state.adapters.length,'plug'],['Profile',state.profiles.length,'adjustments'],['Uruchomienia',state.runs.length,'list-check'],['Oczekują decyzji',state.runs.filter(x=>x.status==='waiting_user').length,'alert-triangle']].map(x=>`<div class="card" style="padding:14px"><i class="ti ti-${x[2]}" style="color:var(--blue)"></i><div style="font-size:24px;font-weight:700">${x[1]}</div><small>${x[0]}</small></div>`).join('')}
    </div>
    <div style="display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:16px">
      <section class="card" style="padding:18px"><h3><i class="ti ti-file-import"></i> Import z dry-run</h3>
        <div style="background:var(--bg3);padding:10px;border-radius:8px;font-size:11px;margin:10px 0">Obsługiwane: CSV, TXT, XLS, XLSX, XLSM, XML, JSON. Pliki Excel są odczytywane lokalnie; makra XLSM nigdy nie są uruchamiane. Limit podglądu: 2000 rekordów.</div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><label class="f"><span>Profil mapowania</span><select id="ih-profile" class="fi"><option value="">— wybierz —</option>${state.profiles.map(p=>`<option value="${E(p.id)}">${E(p.name)} · ${E(p.source_format)}</option>`).join('')}</select></label>
        <label class="f"><span>Plik źródłowy</span><input id="ih-file" class="fi" type="file" accept=".csv,.txt,.xls,.xlsx,.xlsm,.xml,.json" onchange="IntegrationHub.readFile(this.files[0])"></label></div>
        <div id="ih-file-info" style="font-size:12px;color:var(--text3);margin:10px 0">${file?`${E(file.name)} · ${rows.length} rekordów · kolumny: ${E(Object.keys(rows[0]||{}).join(', '))}`:''}</div>
        <button class="btn btn-blue" onclick="IntegrationHub.preview()" ${rows.length?'':'disabled'}><i class="ti ti-search"></i>Uruchom dry-run</button>
        <button class="btn btn-gray" onclick="IntegrationHub.profileDialog()"><i class="ti ti-plus"></i>Nowy profil</button>
        <div id="ih-preview" style="margin-top:14px">${previewHtml()}</div>
      </section>
      <section class="card" style="padding:18px"><h3><i class="ti ti-plug-connected"></i> Adaptery</h3>${state.adapters.map(a=>`<div style="border-bottom:1px solid var(--border);padding:10px 0"><div style="display:flex;justify-content:space-between"><strong>${E(a.name)}</strong>${badge(a.status)}</div><small>${E(a.adapter_key)} · sekret: ${E(a.secret_ref||'nie ustawiono')}</small><div style="margin-top:8px"><button class="btn btn-gray btn-sm" onclick="IntegrationHub.configure('${E(a.id)}')">Konfiguruj</button> <button class="btn btn-gray btn-sm" onclick="IntegrationHub.health('${E(a.id)}')">Test połączenia</button></div></div>`).join('')||'<p>Brak adapterów.</p>'}
      <h3 style="margin-top:18px"><i class="ti ti-file-export"></i> Eksport zleceń</h3><div style="display:flex;gap:6px;flex-wrap:wrap">${['csv','txt','xlsx','xml','json'].map(f=>`<button class="btn btn-gray btn-sm" onclick="IntegrationHub.exportData('${f}')">${f.toUpperCase()}</button>`).join('')}</div>
      <button class="btn btn-gray btn-sm" style="margin-top:10px" onclick="IntegrationHub.scheduleDialog()"><i class="ti ti-clock"></i>Dodaj harmonogram</button></section>
    </div>
    <section class="card" style="padding:18px;margin-top:16px"><h3>Run queue</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Czas</th><th>Operacja</th><th>Źródło</th><th>Status</th><th>Poprawne</th><th>Błędy</th><th>Zastosowane</th></tr></thead><tbody>${state.runs.map(r=>`<tr><td>${E((r.created_at||'').replace('T',' ').slice(0,16))}</td><td>${E(r.operation)}</td><td>${E(r.source_name||'—')}</td><td>${badge(r.status)}</td><td>${r.valid_count||0}</td><td>${r.invalid_count||0}</td><td>${r.applied_count||0}</td></tr>`).join('')||'<tr><td colspan="7">Brak uruchomień</td></tr>'}</tbody></table></div></section>`;}
  function previewHtml(){if(!preview)return '';const r=preview.run||{};return `<div style="border:1px solid ${r.invalid_count?'var(--red)':'var(--green)'};border-radius:8px;padding:12px"><strong>Dry-run:</strong> ${r.valid_count||0} poprawnych · ${r.invalid_count||0} błędnych · ${r.duplicate_count||0} duplikatów ${preview.replayed?'· wynik odtworzony idempotentnie':''}<div style="max-height:180px;overflow:auto;margin-top:8px;font-size:11px">${(preview.items||[]).filter(x=>x.status!=='valid').slice(0,50).map(x=>`<div>Wiersz ${x.row_no}: ${E((x.validation_errors||[]).join?.(', ')||x.validation_errors||x.status)}</div>`).join('')}</div>${!r.invalid_count?`<button class="btn btn-green" onclick="IntegrationHub.commit('${E(r.id)}')"><i class="ti ti-check"></i>Potwierdź import</button>`:'<p style="color:var(--red);font-size:12px">Popraw plik i wykonaj nowy dry-run.</p>'}</div>`;}
  async function readFile(f){file=f;preview=null;rows=[];if(!f)return;try{const ext=(f.name.split('.').pop()||'').toLowerCase();if(['xls','xlsx','xlsm'].includes(ext)){if(!window.XLSX)throw new Error('Biblioteka XLSX niedostępna');const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:false});}else if(ext==='json'){const d=JSON.parse(await f.text());rows=Array.isArray(d)?d:(d.rows||d.data||[]);}else if(ext==='xml'){const text=await f.text();if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('DOCTYPE/ENTITY są niedozwolone');const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Nieprawidłowy XML');rows=[...doc.querySelectorAll('record,row,item')].map(n=>Object.fromEntries([...n.children].map(c=>[c.tagName,c.textContent])));}else rows=parseDelimited(await f.text(),ext==='txt'?'\t':null);draw();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  function parseDelimited(text,forced){const first=(text.replace(/^\uFEFF/,'').split(/\r?\n/)[0]||''),delim=forced||(first.split(';').length>first.split(',').length?';':',');const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),parse=line=>{const out=[];let v='',q=false;for(let i=0;i<=line.length;i++){const c=line[i];if(c==='"'&&q&&line[i+1]==='"'){v+='"';i++;}else if(c==='"')q=!q;else if((c===delim||i===line.length)&&!q){out.push(v);v='';}else v+=c||'';}return out;};const headers=parse(lines.shift()||'').map(x=>x.trim());return lines.map(line=>Object.fromEntries(parse(line).map((v,i)=>[headers[i]||`column_${i+1}`,v])));}
  async function previewRun(){const profile=document.getElementById('ih-profile')?.value;if(!profile||!rows.length)return window.toast?.('Wybierz profil i plik');try{preview=await req('/imports/preview',{method:'POST',body:JSON.stringify({profile_id:profile,source_name:file?.name,rows})});draw();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  async function commit(id){if(!confirm('Zaimportować poprawne rekordy? Ta operacja utworzy zlecenia.'))return;try{const d=await req(`/runs/${id}/commit`,{method:'POST',body:'{}'});window.toast?.(`✅ Zaimportowano ${d.applied}; duplikaty ${d.duplicates}`);preview=null;await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  async function profileDialog(){if(!rows.length)return window.toast?.('Najpierw wybierz plik — nagłówki posłużą do mapowania');const headers=Object.keys(rows[0]||{}),suggest=Object.fromEntries(FIELDS.map(f=>[f,headers.find(h=>h.toLowerCase().replace(/\s+/g,'_')===f)||'']));const name=prompt('Nazwa profilu:',file?.name?`Zlecenia — ${file.name}`:'Import zleceń');if(!name)return;const mappingText=prompt('Mapowanie JSON (pole docelowe: nagłówek pliku):',JSON.stringify(suggest,null,2));if(!mappingText)return;try{const ext=(file.name.split('.').pop()||'csv').toLowerCase();await req('/profiles',{method:'POST',body:JSON.stringify({name,entity_type:'transport_order',source_format:ext,mapping:JSON.parse(mappingText),dedupe_strategy:'external_id'})});window.toast?.('✅ Profil zapisany');await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  async function configure(id){const a=state.adapters.find(x=>x.id===id),old=JSON.parse(a?.config||'{}'),base=prompt('Publiczny adres HTTPS sandboxa ERPNext:',old.base_url||'');if(base===null)return;const ref=prompt('Nazwa sekretu w konfiguracji Workera (bez wartości sekretu):',a.secret_ref||'ERPNEXT_API_TOKEN');if(ref===null)return;try{await req(`/adapters/${id}`,{method:'POST',body:JSON.stringify({config:{mode:'sandbox',base_url:base,api_version:'v2'},secret_ref:ref,status:'inactive'})});await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  async function health(id){try{const d=await req(`/adapters/${id}/health`,{method:'POST',body:'{}'});window.toast?.(`✅ ERPNext: ${d.account||'połączenie działa'}`);await render();}catch(ex){window.toast?.(`⚠ ${ex.message}`);await render();}}
  const safeCell=v=>{const s=String(v??'');return /^[=+\-@]/.test(s)?`'${s}`:s;};
  async function exportData(format){try{const d=await req('/exports/transport-orders'),data=d.rows||[],name=`taxorder_zlecenia_${new Date().toISOString().slice(0,10)}`;if(format==='xlsx'){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,safeCell(v)])))),'Zlecenia');XLSX.writeFile(wb,`${name}.xlsx`);return;}let text,type='text/plain';if(format==='json'){text=JSON.stringify(d,null,2);type='application/json';}else if(format==='xml'){text=`<?xml version="1.0" encoding="UTF-8"?><transport_orders>${data.map(r=>`<record>${Object.entries(r).map(([k,v])=>`<${k}>${E(v)}</${k}>`).join('')}</record>`).join('')}</transport_orders>`;type='application/xml';}else{const sep=format==='txt'?'\t':';',keys=Object.keys(data[0]||{}),cell=v=>`"${safeCell(v).replace(/"/g,'""')}"`;text=[keys.join(sep),...data.map(r=>keys.map(k=>cell(r[k])).join(sep))].join('\r\n');type='text/csv';}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=`${name}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  async function scheduleDialog(){const name=prompt('Nazwa harmonogramu:','Codzienny eksport zleceń');if(!name)return;const format=prompt('Format: csv, txt, xlsx, xml lub json','xlsx');if(!format)return;try{await req('/schedules',{method:'POST',body:JSON.stringify({name,direction:'export',operation:'transport_orders',schedule_kind:'daily',schedule_value:'03:00',export_format:format})});window.toast?.('✅ Harmonogram zapisany w kolejce');await render();}catch(ex){window.toast?.(`❌ ${ex.message}`);}}
  window.IntegrationHub={render,readFile,preview:previewRun,commit,profileDialog,configure,health,exportData,scheduleDialog,parseDelimited};
})();
